// idlakfex/fexfunctions.h

// Copyright 2013 CereProc Ltd.  (Author: Matthew Aylett)

// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
// THIS CODE IS PROVIDED *AS IS* BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, EITHER EXPRESS OR IMPLIED, INCLUDING WITHOUT LIMITATION ANY IMPLIED
// WARRANTIES OR CONDITIONS OF TITLE, FITNESS FOR A PARTICULAR PURPOSE,
// MERCHANTABLITY OR NON-INFRINGEMENT.
// See the Apache 2 License for the specific language governing permissions and
// limitations under the License.
//

#ifndef SRC_IDLAKFEX_FEXFUNCTIONS_H
#define SRC_IDLAKFEX_FEXFUNCTIONS_H

// This file autogenerated by running create_catalog.py
// Do not edit manually

#include "./fex.h"

namespace kaldi {

bool FexFuncCURSTRp(Fex * fex,
                    const pugi::xpath_node_set * nodes,
                    const pugi::xml_node * p,
                    const char * buffer);

}  // namespace kaldi

#endif  // SRC_IDLAKFEX_FEXFUNCTIONS_H_
