.TH acomp 1 "acomp 1.0" "NIST Software"
.SH NAME
acomp - The NIST Automatic Compound Word Division Program for german
.SH SYNOPSIS
.B " acompl.pl [ -t -s ] [ -i fmt ] -m min -l lex Infile|- OutFile|-"

.SH OPTIONS

.IP "\fB-m min\fP"
 Set the minimum length on a compound costituent part to 'min'. Default is 2.

.IP "\fB-l lex\fP"

File name of the LDC German Dictionary
.IP "\fB-t\fP"
Disable the processing of triplet consonants
.IP "\fB-s\fP"
Disable the processing of -s and -en insertions
.IP "\fB-i ( txt | ctm | stm) \fP"
Set the input file formant to 'fmt'.  The possible choices are:

txt -> plain text, the default

ctm -> CTM format, ignores all but the 5th column, and if a division
occurs and a confidence score is present, the confidence score is
copied to all parts.

stm -> STM format, change only the text field of the stm record

.SH DESCRIPTION
.PP

The 'acomp' program expands compound words in German orthography into
the constituent parts of those compound words.  The program uses the
LDC German Lexicon as a basis for the expansions.

.PP

Since this program is designed to be used as a transcript pre-filter
to scoring the LVCSR Hub-5NE tests, it is important that only a single
expansion for each compound be selected.  To that end, the program makes
a series of hierarchical decisions to select the most likely expansion.

.PP

The LDC dictionary has entries for many compound words, in fact, over
50% of the over 300K entries are compounds words.  The entries within
the dictionary are considered to be the most desirable expansions, and
the program uses those entries as such.  If a compound word does not
occur within the dictionary, an automatic procedure is evoked that
attempts to select the single-most likely expansion.

.PP

The algorithm for the automatic compound word division is as follows:

.PP

The LDC German dictionary is parsed and stored into the 'WordSet'
associative array for quick access.  Compound words are processed so
that underscores '_' are removed before insertion into the associative
array.  The constituent parts of compound words are also inserted
into the associative array.  Hyphenated words are similarly processed
except in addition to the transformations outline above, an entry in
the associative array is added for the hyphenated form.

.PP

For speed purposes, another associative array, 'CompSet', is defined
to be the compound words from the dictionary.  During generation of
compound divisions, this list is consulted before the automatic
process is invoked.

.PP

The automatic procedure uses recursion and the two word lists to
exhaustively search all possible combinations of word sequences.  The
search hypothesizes the first N characters as a word where N starts at
the length of the word down to length M, the minimum word length of a
constituent word.  A minimum value of 2 was selected for M to reduce
the number of apparent overgeneration of expansions.

.PP

The hypothesized word is looked up in the 'WordSet' array.  If it
exists, a recursive call is made on the residual word text as being a
valid word or compound word.  If the recursive call successfully
locates a compound word for the residual, recursion terminates,
otherwise the length of the hypothesized word is reduced for another
search.

.PP

German has a number of special ways of changing word spellings when
they are compounded.  When the program hypothesizes a word division,
it takes these rules into account.  The description of the rules that
the program implements are as follows:

.PP

1. Triple Consonants:

.PP

In German, when two words are compounded that result in three adjacent
identical consonants, one consonant is dropped.  The program uses this
rule to identify cases like "bettag" which comes from the words "bett"
and "tag".  The output of the filter then are the root words "bett"
and "tag".  See "CASSELL'S BEYOND THE DICTIONARY IN GERMAN" by
Beautrix Anderson and Maurice North, Library of Congress Number
74-80701.

.PP

2. Insertions of -s and -en

.PP

In German, compounded nouns can have an extra sound or syllable added
between the compounded words.  The program uses this rule to permit
insertions of '-s' and '-en' between compound words.  An example taken
from "A-MORPHOUS MORPHOLOGY" by Stephen R. Anderson, Cambridge
University Press, 1992 would be 'Schwanengesang" or "swan song".  The
two words "Schwan" and "gesang" are joined by the element '-en'.  The
ooutput of the filter will be to output "schwan" and "gesang" deleting
the '-en'.


.SH REVISION HISTORY

acomp 1.0 - Released September 19, 1997

.SH SEE ALSO

