.TH add_kana 1 "add_kana 1.0" "NIST Software"
.SH NAME
add_kana - Add alternate transcripts for kanji words
.SH SYNOPSIS
.B "add_kana <OPTIONS> infile outfile|-"

.SH DESCRIPTION
.PP
The perl script 'add_kana' adds alternate transcriptions to the
CTM file 'infile' if the kanji word can be represented in kana.  The
program reads in the first two columns from the LDC Japanese
dictionary '-d dictionary' then looks up all words in the input CTM
file 'infile' to see if there is an alternate transcription entry for
that word.  If an alternate transcription exists, the filter adds an
alternative transcription to the output file 'outfile'.'  The script
will write the output to stdout if '-' is used for 'outfile'.
.SH OPTIONS

.IP "\fB-d dictionary\fP"
Set the filename of the LDC Japanese dictionary to 'dictionary'

.SH REVISION HISTORY

add_kana 1.0 - Released September 26, 1995

.SH SEE ALSO
sclite(1) ctm(5)
