.TH chfilt 1 "chfilt 1.0" "NIST Software"
.SH NAME
chfilt - Filter Callhome transcriptions
.SH SYNOPSIS
.B "chfilt <OPTIONS> infile outfile|-- -"

.SH DESCRIPTION
.PP

The perl script "chfilt" is a tool for producing derivative
versions of a Callhome transcript.  The current version produced
is STM (Segment Time Marks) for use with 'sclite'.

The tool first reads in a Callhome transcription, 'infile', parses the
transcript then writes the re-formatted transcript to the output
file, 'outfile'.   A double dash and a hyphen '-- -' can be used for 'outfile' to signify stdout.

The parsing involves a language dependent normalization step, however the
output format is not language dependent.

The output format STM is a reference file format used by
'sclite', the new NIST scoring software program.  The file consists of
a concatenation of text segment records corresponding to the speech
from a waveform file(s).  Each record is separated by a newline and
contains: the waveform's filename and channel identifier [A | B], the
talker's id, begin and end times (in seconds) followed by the transcript
for the waveform.  For a complete description of the file format, see the
manual page, 'stm.5', from the "sclite" distribution.
.SH OPTIONS

.IP "\fP-b b_time\fP"
Output is generated beginning with the turn that begins at
or after 'b_time'.  The output continues until the end of transcript unless
the '-e' option is used.
.IP "\fP-e e_time\fP"
Output is generated ending with the turn that ends at
or after 'e_time'.  The output begins at the beginning of the transcript
unless the '-b' options is used.
.IP "\fP-o stm\fP"
Sets the output format to stm (the default).  
.IP "\fP-l [ english | japanese | mandarin | spanish ]\fP"
Set the input language to either English, Japanese, Mandarin or Spanish.
.IP "\fP-i\fP"
Do NOT translate interjections to %INTERJ, leave them as is.
.IP "\fP-I\fP"
Do NOT alternate internate interjections with '@'.
.IP "\fP-q Word1=Word2\fP"
Add alternations to the output such that Word1 and Word2 are equivalent.
.IP "\fP-t Word1=Word2\fP"
Translate Word1 to Word2.
.IP "\fP-a\fP"
Convert all hyphenated words to alternations whereby the two
alternations are the word with hyphens deleted, or" the word(s) with
hyphens converted to spaces

.SH REVISION HISTORY

chfilt 1.0 - Released September 21, 1995

chfilt 1.1 - Released 951006

chfilt 1.2 - Released 951025

chfilt 1.3 - Released 960418

chfilt 1.4 - Released 970711

.SH SEE ALSO
sclite(1) stm(5)