s/<HES_UH>/<hes_uh>/gi
s/<BREATH>/<breath>/gi
s/<PAUSE>/<pause>/gi
s/<MOUTH>/<mouth>/gi
s/<NOISE>/<noise>/gi
s/<HES_UM>/<hes_um>/gi
s/<UNK>/<unk>/gi
s/<SILENCE>/<silence>/gi
s/<LAUGH>/<laugh>/gi
s/<COUGH>/<cough>/gi
s/<HES_EH>/<hes_eh>/gi
s/<EMOTION>/<emotion>/gi
s/<HES_AH>/<hes_ah>/gi
s/<HES_EM>/<hes_em>/gi
s/<HES_OH>/<hes_oh>/gi
s/<HES_UR>/<hes_ur>/gi
s/<HES_ER>/<hes_er>/gi
s/<HES_EN>/<hes_en>/gi
s/<HES_UF>/<hes_uf>/gi
