#!/bin/bash
# bash script to install HTS demos
# Matthew Aylett 08/04/14
# No guarantee this script is future proof. But the result has been tested 20140804

if [ 4 -ne $# ]; then
   echo "install_HTS_demo.sh <HTKID> <HTK PASSWORD> <INSTALL LOCATION> <STRAIGHT MATLAB CODE|\"NOSTRAIGHT\">"
   echo "    4 arguments expected"
   exit 1;
fi

if [ "NOSTRAIGHT" != $4 ] && [ ! -d $4 ]; then
   echo "install_HTS_demo.sh <HTKID> <HTK PASSWORD> <INSTALL LOCATION> <STRAIGHT MATLAB CODE|\"NOSTRAIGHT\">"
   echo "    specify STRAIGHT directory for MATLAB code i.e. /usr/local/STRAIGHTV40_007d or NOSTRAIGHT"
   exit 1;
fi

if [ -d $3 ]; then
    echo "$4 Demo Installing in $3"
else
    mkdir $3
    echo "$4 Demo Creating and installing in $3"
fi

HTKID=$1
HTKPSWD=$2
INSTALL_LOCATION=`readlink -f $3`
STRAIGHT=$4
PWD=`pwd`

cd $INSTALL_LOCATION
echo cd $INSTALL_LOCATION
mkdir installdir

wget http://htk.eng.cam.ac.uk/ftp/software/HTK-3.4.1.tar.gz --http-user=$HTKID --http-password=$HTKPSWD

wget http://htk.eng.cam.ac.uk/ftp/software/hdecode/HDecode-3.4.1.tar.gz --http-user=$HTKID --http-password=$HTKPSWD

wget http://hts.sp.nitech.ac.jp/archives/2.3alpha/HTS-2.3alpha_for_HTK-3.4.1.tar.bz2

## Unpack everything:
tar -zxvf HTK-3.4.1.tar.gz
tar -zxvf HDecode-3.4.1.tar.gz
tar -xvf HTS-2.3alpha_for_HTK-3.4.1.tar.bz2

## Apply HTS patch:
cd htk
patch -p1 -d . < ../HTS-2.3alpha_for_HTK-3.4.1.patch



## Finally, configure and compile:
./configure --prefix=$INSTALL_LOCATION/installdir --without-x --disable-hslab
make
make install
cd ..

# sptk

wget http://downloads.sourceforge.net/sp-tk/SPTK-3.6.tar.gz
tar xvfz  SPTK-3.6.tar.gz
cd SPTK-3.6
./configure --prefix=$INSTALL_LOCATION/installdir
make -j 4
make install
cd ..

# hts engine

wget http://downloads.sourceforge.net/hts-engine/hts_engine_API-1.07.tar.gz
tar xvfz hts_engine_API-1.07.tar.gz
cd hts_engine_API-1.07
./configure --prefix=$INSTALL_LOCATION/installdir CFLAGS="-m32 -g -O2 -Wall"
make -j 4
make install
cd ..

# speech tools
wget http://www.cstr.ed.ac.uk/downloads/festival/2.1/speech_tools-2.1-release.tar.gz
tar xfvz speech_tools-2.1-release.tar.gz
cd speech_tools
./configure
make
cd ..
# festival
wget http://www.cstr.ed.ac.uk/downloads/festival/2.1/festival-2.1-release.tar.gz
tar xvfz festival-2.1-release.tar.gz
cd festival
./configure
make
cd ..

wget http://www.cstr.ed.ac.uk/downloads/festival/2.1/festlex_CMU.tar.gz
wget http://www.cstr.ed.ac.uk/downloads/festival/2.1/festvox_cmu_us_slt_arctic_hts.tar.gz

tar xvfz festlex_CMU.tar.gz
tar xvfz festvox_cmu_us_slt_arctic_hts.tar.gz

if [ "NOSTRAIGHT" == "$STRAIGHT" ]; then
    wget http://hts.sp.nitech.ac.jp/archives/2.3alpha/HTS-demo_CMU-ARCTIC-SLT.tar.bz2
    tar xvfj HTS-demo_CMU-ARCTIC-SLT.tar.bz2
    cd HTS-demo_CMU-ARCTIC-SLT
    echo ./configure --with-fest-search-path=$INSTALL_LOCATION/festival/examples \
                     --with-sptk-search-path=$INSTALL_LOCATION/installdir/bin \
                     --with-hts-search-path=$INSTALL_LOCATION/installdir/bin \
                     --with-hts-engine-search-path=$INSTALL_LOCATION/installdir/bin > config.txt
cd ..
else
    # get STRAIGHT (Only possible if you are at an IP address that has been set up for download
    # otherwise you will need to contact Professor Kawahara directly to get permisssion and the matlab 
    # source code.
    #
    # wget http://www.wakayama-u.ac.jp/~kawahara/puzzlet/STRAIGHTtipse/Resources/STRAIGHTV40_007d.zip
    # unzip STRAIGHTV40_007d.zip
    # NOTE this version of STRAIGHT does not work with this HTS-demo.
    # wget http://www.wakayama-u.ac.jp/~kawahara/puzzlet/STRAIGHTtipse/Resources/STRAIGHTV40_005b.tar.gz
    # tar xvfz STRAIGHTV40_005b.tar.gz
    # wavs generated by sptk raw2wav in the demo are not in the correct format for MATLAB so you will
    # need to do
    # ../../speech_tools/bin/ch_wave -f 48000 -itype raw -o wav/cmu_us_arctic_slt_b0538.wav raw/cmu_us_arctic_slt_b0538.raw
    # or something similar using sox
    wget http://hts.sp.nitech.ac.jp/archives/2.3alpha/HTS-demo_CMU-ARCTIC-SLT_STRAIGHT.tar.bz2
    tar xvfj HTS-demo_CMU-ARCTIC-SLT_STRAIGHT.tar.bz2
    #unzip STRAIGHTtrial.zip
    cd HTS-demo_CMU-ARCTIC-SLT_STRAIGHT 
    echo ./configure --with-matlab-search-path=/usr/bin \
                     --with-straight-path=$STRAIGHT \
                     --with-fest-search-path=$INSTALL_LOCATION/festival/examples \
                     --with-sptk-search-path=$INSTALL_LOCATION/installdir/bin \
                     --with-hts-search-path=$INSTALL_LOCATION/installdir/bin \
                     --with-hts-engine-search-path=$INSTALL_LOCATION/installdir/bin > config.txt
cd ..
fi

cd $PWD

# to run configuration
# cd $INSTALL_LOCATION/HTS-demo_CMU-ARCTIC-SLT
# or for STRAIGHT demo
# cd $INSTALL_LOCATION/HTS-demo_CMU-ARCTIC-SLT_STRAIGHT
# You can alter configuration aspects here (required for using your own data)
# ./configure -h
# gives options otherwise
# source config.txt
# ./configure
#export LD_LBRARY_PATH=$INSTALL_LOCATION/installdir/lib:$LD_LBRARY_PATH

# Note make will first do data extraction (which takes an hour or so)
# in an active terminal window and then do training in the background
# This takes longer then a standard AFS token so will fail without 
# using longer length tokens. This will probably work if you run make 
# using a long life token.

# alternatively you could install to scratch you can't copy the demo 
# to another location as there are numerous hard coded paths in the 
# system.

# Note if you want to use the kaldi front end look at the Idlak 
# documentation before building;.


